### ISSUE TITLE
regression: geometer waveform view and large help icon are gone on win32

### ISSUE THREAD

**Issue by tom7** [sophiapoirier/destroyfx#32]

**Comment by sophiapoirier** [comment]
I'm curious if moving to VSTGUI 4.10 in 812e42e might have changed this?

**Comment by tom7** [comment]
I just checked everything out including the new VSTGUI (see my recent push for windows fix) and indeed I don't see this any more? It's also possible that this was self-inflicted because I was futzing around in vstgui trying to debug direct pixel access for brokenfft GUI, but cleared out that stuff in order to update the submodule. In any case, good news!

**Comment by tom7** [comment]
"fixed" or "not reproducible" 😎
